<?php

namespace App\Console\Commands;

use App\Models\Icon;
use App\Support\IconCatalogue;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * Loads database/data/icons.json into the `icons` table. Runs on every
 * container boot, so it compares a checksum against what was last loaded and
 * no-ops on a match. The file is generated by `npm run icons:build` and
 * committed rather than built server-side — PHP can't regenerate it, so a
 * failed build there would silently lose every icon on the site.
 */
class SyncIconCatalogue extends Command
{
    protected $signature = 'icons:sync {--force : Reload even when the catalogue is unchanged}';

    protected $description = 'Load the generated icon catalogue into the database';

    public function handle(): int
    {
        $path = database_path('data/icons.json');

        if (! is_file($path)) {
            $this->components->error("No icon catalogue at {$path}.");
            $this->line('  Run `npm run icons:build` to generate it.');

            return self::FAILURE;
        }

        // A read failure returns false; storing that as an empty string would
        // never match a real checksum, silently reloading all rows every boot.
        $checksum = hash_file('xxh128', $path);

        if ($checksum === false) {
            $this->components->error(sprintf('Could not read the icon catalogue at %s.', $path));

            return self::FAILURE;
        }

        if (! $this->option('force') && $this->storedChecksum() === $checksum) {
            $this->components->info('Icon catalogue already up to date.');

            return self::SUCCESS;
        }

        /** @var array<string, array<int, mixed>>|null $catalogue */
        $catalogue = json_decode((string) file_get_contents($path), true);

        if (! is_array($catalogue) || $catalogue === []) {
            $this->components->error('The icon catalogue is empty or not valid JSON.');

            return self::FAILURE;
        }

        $rows = [];

        foreach ($catalogue as $key => $nodes) {
            [$library, $name] = array_pad(explode(':', (string) $key, 2), 2, null);

            if ($name === null || ! array_key_exists($library, IconCatalogue::LIBRARIES)) {
                continue;
            }

            $rows[] = [
                'key' => $key,
                'library' => $library,
                'name' => $name,
                'nodes' => json_encode($nodes),
            ];
        }

        // Replace wholesale rather than diffing. This is derived data with no
        // authored state to preserve, and a rename in an upstream package
        // should drop the old row rather than leave it behind forever.
        DB::transaction(function () use ($rows) {
            Icon::query()->delete();

            foreach (array_chunk($rows, 1000) as $chunk) {
                Icon::query()->insert($chunk);
            }
        });

        $this->rememberChecksum($checksum);

        $this->components->info(sprintf('Loaded %s icons.', number_format(count($rows))));

        return self::SUCCESS;
    }

    /**
     * Kept in the database next to the data it describes, so a restored
     * backup and its catalogue can never disagree. Rides in `settings`
     * rather than its own table; `SiteSettings` only reads its own
     * whitelisted keys, so this row stays invisible to it.
     */
    private function storedChecksum(): ?string
    {
        if (! Icon::query()->exists()) {
            return null;
        }

        $stored = DB::table('settings')
            ->where('key', 'icon_catalogue_checksum')
            ->value('value');

        return is_string($stored) ? json_decode($stored, true) : null;
    }

    private function rememberChecksum(string $checksum): void
    {
        DB::table('settings')->updateOrInsert(
            ['key' => 'icon_catalogue_checksum'],
            [
                'value' => json_encode($checksum),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        );
    }
}
