<?php

namespace App\Console\Commands;

use App\Models\Icon;
use App\Support\IconCatalogue;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

/**
 * Loads database/data/icons.json into the `icons` table.
 *
 * Runs from the container entrypoint on every boot, so it has to be
 * idempotent and cheap when nothing changed — it compares a checksum of the
 * generated file against what was last loaded and does nothing if they match.
 *
 * The file itself is generated by `npm run icons:build` from the icon
 * packages' own exported data. It is committed rather than built on the
 * server because PHP has no way to regenerate it: a deploy that could not
 * produce it would silently lose every icon on the site.
 */
class SyncIconCatalogue extends Command
{
    protected $signature = 'icons:sync {--force : Reload even when the catalogue is unchanged}';

    protected $description = 'Load the generated icon catalogue into the database';

    public function handle(): int
    {
        $path = database_path('data/icons.json');

        if (! is_file($path)) {
            $this->components->error("No icon catalogue at {$path}.");
            $this->line('  Run `npm run icons:build` to generate it.');

            return self::FAILURE;
        }

        // false on a read failure. Stored as-is that becomes an empty string,
        // which can never equal the checksum of a real file — so `icons:sync`
        // would reload all fifteen thousand rows on every container boot and
        // nothing would say why. It runs from the entrypoint, so that is a
        // slower start for the life of the deployment.
        $checksum = hash_file('xxh128', $path);

        if ($checksum === false) {
            $this->components->error(sprintf('Could not read the icon catalogue at %s.', $path));

            return self::FAILURE;
        }

        if (! $this->option('force') && $this->storedChecksum() === $checksum) {
            $this->components->info('Icon catalogue already up to date.');

            return self::SUCCESS;
        }

        /** @var array<string, array<int, mixed>>|null $catalogue */
        $catalogue = json_decode((string) file_get_contents($path), true);

        if (! is_array($catalogue) || $catalogue === []) {
            $this->components->error('The icon catalogue is empty or not valid JSON.');

            return self::FAILURE;
        }

        $rows = [];

        foreach ($catalogue as $key => $nodes) {
            [$library, $name] = array_pad(explode(':', (string) $key, 2), 2, null);

            if ($name === null || ! array_key_exists($library, IconCatalogue::LIBRARIES)) {
                continue;
            }

            $rows[] = [
                'key' => $key,
                'library' => $library,
                'name' => $name,
                'nodes' => json_encode($nodes),
            ];
        }

        // Replace wholesale rather than diffing. This is derived data with no
        // authored state to preserve, and a rename in an upstream package
        // should drop the old row rather than leave it behind forever.
        DB::transaction(function () use ($rows) {
            Icon::query()->delete();

            foreach (array_chunk($rows, 1000) as $chunk) {
                Icon::query()->insert($chunk);
            }
        });

        $this->rememberChecksum($checksum);

        $this->components->info(sprintf('Loaded %s icons.', number_format(count($rows))));

        return self::SUCCESS;
    }

    /**
     * The checksum is kept in the database next to the data it describes, so
     * a restored backup and its catalogue can never disagree.
     *
     * It rides in `settings` to avoid a table holding a single string.
     * `SiteSettings` reads only its own whitelisted keys, so this row is
     * invisible to everything else.
     */
    private function storedChecksum(): ?string
    {
        if (! Icon::query()->exists()) {
            return null;
        }

        $stored = DB::table('settings')
            ->where('key', 'icon_catalogue_checksum')
            ->value('value');

        return is_string($stored) ? json_decode($stored, true) : null;
    }

    private function rememberChecksum(string $checksum): void
    {
        DB::table('settings')->updateOrInsert(
            ['key' => 'icon_catalogue_checksum'],
            [
                'value' => json_encode($checksum),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        );
    }
}
