#!/bin/sh
#
# Container entrypoint. Runs on every start, so everything here must be
# idempotent — a restart is not a fresh install.

set -eu

log() { echo "[entrypoint] $*"; }

# Named volumes over storage/ mount root-owned and empty while PHP-FPM runs as
# www-data; without this, Laravel can't write its own log and fails inside its
# own error handler. Only relevant in development (runs as root); production
# ships correct ownership already.
if [ "$(id -u)" = '0' ]; then
    chown -R www-data:www-data storage bootstrap/cache 2>/dev/null || true
fi

# Development only: vendor/ lives in a named volume that starts empty, so the
# first `up` has no autoloader. Production ships vendor/ baked in.
if [ "${APP_ENV:-production}" != "production" ] && [ ! -f vendor/autoload.php ]; then
    log "No vendor/autoload.php — installing PHP dependencies (first run only)."
    composer install --no-interaction --prefer-dist
fi

# Everything below boots the application, not a one-off `run` command — a
# plain `docker compose run --rm app php artisan …` must not migrate the
# database as a side effect, and the APP_KEY guard below would otherwise block
# the very `key:generate` it tells you to run. Only affects `run`; `exec`
# bypasses the entrypoint entirely.
if [ "${1:-php-fpm}" != 'php-fpm' ]; then
    exec "$@"
fi

if [ -z "${APP_KEY:-}" ]; then
    log "FATAL: APP_KEY is not set."
    log "Generate one with: docker compose run --rm app php artisan key:generate --show"
    log "then put it in .env as APP_KEY=base64:..."
    exit 1
fi

# A database still replaying WAL accepts TCP connections while refusing
# queries, so verify with a real connection rather than a port probe.
log "Waiting for PostgreSQL at ${DB_HOST:-database}:${DB_PORT:-5432} ..."
attempt=0
until php -r '
    $dsn = sprintf("pgsql:host=%s;port=%s;dbname=%s",
        getenv("DB_HOST") ?: "database",
        getenv("DB_PORT") ?: "5432",
        getenv("DB_DATABASE"));
    new PDO($dsn, getenv("DB_USERNAME"), getenv("DB_PASSWORD"),
        [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
' 2>/dev/null; do
    attempt=$((attempt + 1))
    if [ "$attempt" -ge 60 ]; then
        log "FATAL: PostgreSQL did not become available after 2 minutes."
        exit 1
    fi
    sleep 2
done
log "PostgreSQL is ready."

# --force skips the interactive confirmation; migrations are additive and
# safe to re-run.
log "Running migrations ..."
php artisan migrate --force --no-interaction

# Pre-seeds the admin account from ADMIN_* env vars if configured; a no-op
# after the first boot.
php artisan admin:seed --no-interaction

# Starting data (education levels), seeded rather than hardcoded so the owner
# can rename/reorder. Must stay idempotent — runs every boot and must never
# resurrect a level the owner deleted.
php artisan db:seed --force --no-interaction

# Icon catalogue geometry, generated by `npm run icons:build` and committed as
# database/data/icons.json. Kept out of db:seed since it's derived data, not
# content; a checksum makes an unchanged run a no-op.
php artisan icons:sync --no-interaction

# Clears abandoned upload chunks, which live on the backed-up media volume and
# would otherwise persist into every backup indefinitely.
php artisan media:prune-uploads --no-interaction

# Built at start, not at image build time, since caches bake in runtime env
# values unknown at build time.
if [ "${APP_ENV:-production}" = "production" ]; then
    log "Caching configuration, routes and views ..."
    php artisan config:cache --no-interaction
    php artisan route:cache --no-interaction
    php artisan view:cache --no-interaction
else
    log "Development environment — clearing caches instead of building them."
    php artisan config:clear --no-interaction
    php artisan route:clear --no-interaction
    php artisan view:clear --no-interaction
fi

log "Ready."
exec "$@"
