<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // Icon catalogue geometry, generated by scripts/build-icon-catalogue.mjs
        // and loaded by `php artisan icons:sync`. Lives in the DB, not a PHP
        // array or JS bundle: 4.9 MB across ~15,000 icons, and a page shows
        // only a handful via keyed lookup. Derived data — icons:sync may
        // replace it wholesale.
        Schema::create('icons', function (Blueprint $table) {
            // "library:name" (e.g. lucide:atom) — the same string stored in
            // topics.icon/pages.icon, keeping lookups a plain whereIn.
            $table->string('key')->primary();

            // Denormalised from the key for per-library filtering.
            $table->string('library')->index();

            // The key's searchable part, without the library prefix.
            $table->string('name')->index();

            // [tag, attributes] pairs, lucide's own shape — structured data,
            // never markup, so the renderer never injects HTML.
            $table->jsonb('nodes');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('icons');
    }
};
